# Generated by Django 5.0.1 on 2024-02-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default='Image/None/Noimg.jp', upload_to='images/'),
        ),
    ]
