# Generated by Django 5.0.1 on 2024-02-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('ename', models.CharField(max_length=50)),
                ('esalary', models.FloatField()),
            ],
        ),
    ]
